logging:
#  path: C:\0.D\Dev\Web\xzs-mysql\source\xzs\log
    path: /www/xzs/log

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xzs?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: netsain123456
    driver-class-name: com.mysql.cj.jdbc.Driver
